export const POST_KCCQ_QUESTION = "POST_KCCQ_QUESTION"
export const POST_KCCQ_QUESTION_ERR = "POST_KCCQ_QUESTION_ERR"
export const POST_KCCQ_REMARK_ERR = "POST_KCCQ_REMARK_ERR"
export const POST_KCCQ_REMARK = "POST_KCCQ_REMARK"
export const GET_GENERATE_ID = "GET_GENERATE_ID"
export const GET_GENERATE_ID_ERR ="GET_GENERATE_ID_ERR"
export const CREATE_PATIENT_ERR = "CREATE_PATIENT_ERR"
export const CREATE_PATIENT = "CREATE_PATIENT"
export const GET_ALL_PATIENT_ERR = "GET_ALL_PATIENT_ERR"
export const GET_ALL_PATIENT = "GET_ALL_PATIENT"
export const GET_PATIENT_DATA_ERR = "GET_PATIENT_DATA_ERR"
export const GET_PATIENT_DATA = "GET_PATIENT_DATA"
export const POST_CREATININE_ERR = "POST_CREATININE_ERR"
export const POST_CREATININE = "POST_CREATININE"
export const POST_CYS_CREATININE_ERR = "POST_CYS_CREATININE_ERR"
export const POST_CYS_CREATININE = "POST_CYS_CREATININE"
export const POST_LV_EJECTION_ERR = "POST_LV_EJECTION_ERR"
export const POST_LV_EJECTION = "POST_LV_EJECTION"


//New

export const WALLET_ADDRESS= "WALLET_ADDRESS";
export const GET_MERKLE_TREE = "GET_MERKLE_TREE";
export const GET_HASH = "GET_HASH";
export const GET_PROOF="GET_PROOF";
export const GET_ROOT = "GET_ROOT";
export const VERIFY_PROOF = "VERIFY_PROOF";